[theme]
primaryColor = "#4316e9"
backgroundColor = "#0D1117"
secondaryBackgroundColor = "#0e0530"
textColor = "#fcfcfd"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false
