[theme]
primaryColor = "#f00f5a"
backgroundColor = "#181818"
secondaryBackgroundColor = "#1F1F1F"
textColor = "#fcfcfd"
font = "sans serif"

[server]
maxUploadSize = 100
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false
