[theme]
primaryColor = "#f00f5a"
backgroundColor = "#0D1117"
secondaryBackgroundColor = "#232e3e"
textColor = "#fcfcfd"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = false
enableCORS = false

[browser]
gatherUsageStats = false
